### ISSUE TITLE
Cannot convert from CBZ to PDF

### ISSUE THREAD

**Issue by martinkirov** [potatoeggy/mandown#55]
i tried running:

`mandown convert pdf (comic.cbz)`

and I got:

`Comic not found at (comic), is md-metadata.json missing?`

Im not sure what this means, have you had this when trying to convert cbz to pdf? 

Cheers,

**Comment by potatoeggy** [comment]
Hi,

Mandown doesn't support coverting *between* comic formats and expects a folder of image folders.

In your case, since you have a CBZ file, you can rename it to a .zip file, extract it somewhere, and follow the instructions here  https://github.com/potatoeggy/mandown/blob/master/docs/converting.md#converting-external-comics  to get the PDF.

Hope this helps!

**Comment by potatoeggy** [comment]
This is now natively supported! `mandown convert pdf (comic).cbz` will now do exactly as you'd expect.

**Comment by martinkirov** [comment]
hey, apologies i didnt reply on the earlier message. Thanks for adding this as a feature!!
